"""Collect Python source from this machine so Flow can learn what code looks like.

No network. The Python standard library and the installed packages are already
on disk, and they are unusually good training data: consistently formatted,
heavily commented, and written by people who cared.

Docstrings and comments are kept on purpose. They are the bridge between
English and code — the only thing that teaches a model that the words above a
function have something to do with the function.

Run:  .venv/bin/python model/build_code_corpus.py
Gate: >= 10 MB collected, >= 500 files, >= 90% printable ASCII.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")
OUT = os.path.join(DATA, "code.txt")

ROOTS = [
    "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework"
    "/Versions/3.9/lib/python3.9",
    "/Users/gefen/flow/.venv/lib/python3.9/site-packages",
]

MIN_BYTES = 300
MAX_BYTES = 60_000        # a few enormous generated files would dominate
MAX_TOTAL = 30 * 1024 * 1024
SKIP = ("test", "tests", "__pycache__", "site-packages/pip", "lib2to3",
        "idlelib", "encodings", "_distutils")


def looks_generated(text):
    """Skip machine-written files: they teach patterns no human would write."""
    head = text[:2000].lower()
    if "do not edit" in head or "autogenerated" in head or "auto-generated" in head:
        return True
    lines = text.split("\n")
    if not lines:
        return True
    # Generated files tend to have very long lines; real source does not.
    long_lines = sum(1 for ln in lines if len(ln) > 200)
    return long_lines > len(lines) * 0.1


def collect():
    seen = 0
    files = 0
    chunks = []
    for root in ROOTS:
        if not os.path.isdir(root):
            print(f"  missing: {root}")
            continue
        for dirpath, dirnames, filenames in os.walk(root):
            if any(s in dirpath for s in SKIP):
                dirnames[:] = []
                continue
            for name in sorted(filenames):
                if not name.endswith(".py"):
                    continue
                path = os.path.join(dirpath, name)
                try:
                    size = os.path.getsize(path)
                    if not (MIN_BYTES <= size <= MAX_BYTES):
                        continue
                    with open(path, encoding="utf-8", errors="ignore") as f:
                        text = f.read()
                except OSError:
                    continue
                if looks_generated(text):
                    continue
                # Separate files the same way the story corpus separates
                # stories, so the model learns where one file ends.
                chunks.append(text.rstrip() + "\n<|endoftext|>\n")
                seen += len(text)
                files += 1
                if seen >= MAX_TOTAL:
                    print(f"  hit {MAX_TOTAL / 1e6:.0f} MB cap")
                    return chunks, files, seen
        print(f"  {root.split('/')[-1]}: {files} files so far")
    return chunks, files, seen


def main():
    os.makedirs(DATA, exist_ok=True)
    print("collecting Python source from this machine\n")
    chunks, files, seen = collect()

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("".join(chunks))

    with open(OUT, encoding="utf-8") as f:
        text = f.read()

    size_mb = len(text) / 1e6
    sample = text[:2_000_000]
    printable = sum(1 for c in sample if 32 <= ord(c) < 127 or c in "\n\t")
    ascii_pct = 100.0 * printable / max(len(sample), 1)

    checks = [
        ("size >= 10 MB", size_mb >= 10, f"{size_mb:.1f} MB"),
        ("files >= 500", files >= 500, f"{files:,}"),
        ("printable ASCII >= 90%", ascii_pct >= 90, f"{ascii_pct:.1f}%"),
    ]

    print(f"\nwrote {OUT}")
    print("\n=== CODE CORPUS GATE ===")
    for name, passed, detail in checks:
        print(f"{'PASS' if passed else 'FAIL'}  {name}: {detail}")

    print("\n--- sample ---")
    print(text[:400])

    ok = all(c[1] for c in checks)
    print(f"\n{'CODE CORPUS READY' if ok else 'NOT READY'}")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
